version: '3.8'
services:
  backend:
    build:
      context: ./fileSys
      dockerfile: dockerfile
    container_name: filesys-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge